### ISSUE TITLE
when turning on secondary monitor, top margin for primary monitor disappears

### ISSUE THREAD

**Issue by maxfinnsjo** [programical/pytyle1x#9]
- xfce
- default example config file

**Comment by programical** [comment]
If you send the tile command (<kbd>Super</kbd>-<kbd>A</kbd> in the default config), does the margin return?

**Comment by maxfinnsjo** [comment]
> If you send the tile command (Super-A in the default config), does the margin return?

Super-A does not make the top margin return to default. 

When I disable secondary monitor, top margin is restored on primary monitor instantly as per default settings.

**Comment by programical** [comment]
I can't currently work on this, as it requires access to two monitors.

**Comment by programical** [comment]
If you want to use margins with multiple screens, you have to use the work area configuration option. See [Configuration#work-area](https://github.com/programical/pytyle1x/wiki/Configuration#work-area).
